version: '3.9'
services:
  user:
    build: .
    environment:
      - DJANGO_SECRET_KEY=django-insecure-_zk=9yl=ul!po@_z-)wq&x4=&!(ons2(pogyu52+f7f37v3j$y
      - EMAIL_USER=waddah.20121999@gmail.com
      - EMAIL_PASS=kfgzqalucyeodtrq
      - EMAIL_FROM=waddah.20121999@gmail.com
      - JWT_SECTET_KEY=yigayiwgowahawjjopawj
    command: python manage.py runserver 0.0.0.0:9000

    ports:
      - "9000:9000"

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database 